local Events = {
	STATE_CHANGED = "state_changed",
	FLIPPED = "flipped",
	GROUNDED_CHANGED = "grounded_changed",
	SLOWDOWN_CHANGED = "slowdown_changed",
	SLOWDOWN_ENTER = "slowdown_enter",
	SLOWDOWN_EXIT = "slowdown_exit",
	ANIM_FRAME = "anim_frame",
	PROP_HIT = "prop_hit",
	PROP_BROKEN = "prop_broken",
	SWING = "swing",
	FOLLOW_ARRIVED = "follow_arrived",
	TWEEN_COMPLETED = "tween_completed",
	PICKUP = "pickup",
	PROP_SPAWNED = "prop_spawned",
	VALUE_CHANGED = "value_changed",
	COUNTER_TICK = "counter_tick",
	COUNTER_WRAP = "counter_wrap",
}
return Events