<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

        <RollForward>Major</RollForward>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Roslynator.Analyzers" Version="4.12.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Content\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <Target Name="FormatOnBuild" BeforeTargets="Build">
        <Exec Command="dotnet csharpier format ." />
    </Target>
</Project>
